---
- name: Get landscape server SSL public key (self-hosted)
  ansible.builtin.slurp:
    src: "{{ landscape_client_server_ssl_cert }}"
  become: true
  register: "_landscape_client_ssl_cert"
  delegate_to: "{{ landscape_client_server }}"
  when: landscape_client_server_self_hosted

- name: Ensure landscape server SSL public key is set (self-hosted)
  ansible.builtin.template:
    src: "etc/landscape/server.pem.j2"
    dest: "{{ landscape_client_ssl_cert }}"
    mode: 0644
  become: true
  when: landscape_client_server_self_hosted

- name: Configure landscape client
  ansible.builtin.template:
    src: "etc/landscape/client.conf.j2"
    dest: "/etc/landscape/client.conf"
    owner: "landscape"
    group: "root"
    mode: 0644
  become: true
  notify: "restart landscape-client"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
