---
- name: config | Capture Landscape Server SSL public key (Self-Hosted)
  slurp:
    src: "{{ landscape_client_server_ssl_cert }}"
  become: true
  register: "_landscape_client_ssl_cert"
  delegate_to: "{{ landscape_client_server }}"
  when: landscape_client_server_self_hosted

- name: config | Add Landscape Server SSL public key (Self-Hosted)
  template:
    src: "etc/landscape/server.pem.j2"
    dest: "{{ landscape_client_ssl_cert }}"
  become: true
  when: landscape_client_server_self_hosted

- name: config | Configure Landscape Client
  template:
    src: "etc/landscape/client.conf.j2"
    dest: "/etc/landscape/client.conf"
    owner: "landscape"
    group: "root"
    mode: "u=rw,g=,o="
  become: true
  notify:
    - "restart landscape-client"

- meta: flush_handlers
