---
- name: "Ensure landscape client is installed"
  ansible.builtin.apt:
    name:
      - "landscape-client"
      - "openssl"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
