---
# tasks file for landscape_client
- name: landscape client
  block:
    - include_tasks: ubuntu.yml
    - include_tasks: config.yml
    - include_tasks: register.yml
  when: ansible_distribution == "Ubuntu"
