---
# tasks file for ansible-role-andscape-client
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config.yml
  when: ansible_os_family == "Debian"

- include: register.yml
  when: ansible_os_family == "Debian"
