---
# tasks file for landscape_client

- name: "Gather facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Become block"
  become: true
  block:
    - name: "Install Landscape"
      ansible.builtin.include_tasks: install.yml
      when: ansible_distribution == "Ubuntu"

    - name: "Configure Landscape"
      ansible.builtin.include_tasks: config.yml
      when: ansible_distribution == "Ubuntu"

    - name: "Register Landscape"
      ansible.builtin.include_tasks: register.yml
      when: ansible_distribution == "Ubuntu"
