---
# tasks file for ansible-role-andscape-client
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: config.yml
  when: ansible_os_family == "Debian"

- include_tasks: register.yml
  when: ansible_os_family == "Debian"
