---
#- name: register | Check if Client is Already Registered
#  stat:
#    path: "/etc/landscape/.client_registered"
#  become: true
#  register: "_landscape_client_registered_check"

- name: register | Registering Client
  command: >
           landscape-config --silent
  become: true
#  register: "_landscape_client_registered"
#  when: not _landscape_client_registered_check['stat']['exists']

#- name: register | Mark Client As Registered
#  file:
#    path: "/etc/landscape/.client_registered"
#    state: "touch"
#  become: true
#  when: _landscape_client_registered['changed']
