---
- name: Check if landscape client is already registered
  ansible.builtin.stat:
    path: "/etc/landscape/.client_registered"
  become: true
  register: "_landscape_client_registered_check"
  when: not landscape_client_force_register

- name: Register landscape client
  become: true
  ansible.builtin.command: >
    landscape-config --silent
  register: "_landscape_client_registered"
  notify: "mark client as registered"
  when: landscape_client_force_register or not _landscape_client_registered_check['stat']['exists']
