---
- name: register | Check if Client is Already Registered
  ansible.builtin.stat:
    path: "/etc/landscape/.client_registered"
  become: true
  register: "_landscape_client_registered_check"
  when: not landscape_client_force_register

- name: register | Registering Client
  ansible.builtin.command: >
    landscape-config --silent
  become: true
  register: "_landscape_client_registered"
  # yamllint disable-line rule:line-length
  when: landscape_client_force_register or not _landscape_client_registered_check['stat']['exists']

- name: flush handlers
  ansible.builtin.meta: flush_handlers
