---
- name: "Check if landscape client is already registered"
  become: true
  ansible.builtin.stat:
    path: "/etc/landscape/.client_registered"
  register: "_landscape_client_registered_check"
  when: not landscape_client_force_register

- name: "Register landscape client" # noqa no-changed-when
  become: true
  ansible.builtin.command: >
    landscape-config --silent
  register: "_landscape_client_registered"
  notify: "Mark client as registered"
  tags:
    - "molecule-notest"
  when: landscape_client_force_register or not _landscape_client_registered_check['stat']['exists']
