---
# handlers file for ansible-role-landscape_client
- name: Restart landscape-client
  ansible.builtin.service:
    name: "landscape-client"
    state: "restarted"
  become: true

- name: Mark client as registered
  ansible.builtin.file:
    path: "/etc/landscape/.client_registered"
    state: "touch"
    mode: 0644
  become: true
