---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "landscape-client-${distro:-ubuntu2204}-${tag:-latest}"
    image: geerlingguy/docker-${distro:-ubuntu2204}-ansible:${tag:-latest}
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
