---
- name: "Verify"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Run landscape-client --version"
      ansible.builtin.command:
        cmd: landscape-client --version
      when: ansible_distribution == "Ubuntu"

    - name: "Check if connection still works"
      ansible.builtin.ping:
