---
name: Ansible Molecule
on:
  push:
  pull_request:
  schedule:
    - cron: "47 22 24 * *"

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main

  molecule:
    name: Molecule
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "focal"
          - image: "ubuntu"
            tag: "bionic"
          - image: "rockylinux"
            tag: "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v2

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_IMAGE: ${{ matrix.image }}
          MOLECULE_TAG: ${{ matrix.tag }}
