---
#
# Ansible managed
#

name: Ansible Molecule
on:
  push:
  pull_request:
  schedule:
    - cron: "3 2 2 * *"
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "focal"
          - image: "ubuntu"
            tag: "bionic"
          - image: "debian"
            tag: "latest"
          - image: "enterpriselinux"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
